instagram_web/blueprints/users/views.py
from flask import Blueprint, render_template,request,redirect,url_for
from models.user import User_ as u 
from werkzeug.security import generate_password_hash

users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/new', methods=['GET'])
def new():
    return render_template('users/new.html')


@users_blueprint.route('/', methods=['POST'])
def create():
    
    username = request.form.get('username')
    password = generate_password_hash(request.form.get('password'))
    email = request.form.get('email')
    u(username=username,password=password,email=email).save()
    return redirect(url_for('home'))



@users_blueprint.route('/<username>', methods=["GET"])
def show(username):
    pass

@users_blueprint.route('/', methods=["GET"])
def index():
    return "USERS"


@users_blueprint.route('/<id>/edit', methods=['GET'])
def edit(id):
    pass


@users_blueprint.route('/<id>', methods=['POST'])
def update(id):
    pass

instagram_web/blueprints/users/templates/users/new.html
{% extends "_layout.html" %} {% block content %}
<h1>Sign up here!</h1>
<div>
  <form action="{{ url_for('users.create') }}" method="POST">
    <div class="form-group">
      <label for="username">Username:</label>
      <input type="hidden" name="csrf_token" value="{{ csrf_token }}" />
      <input type="text" name="username" class="form-control" id="username" />
    </div>

    <div class="form-group">
      <label for="password"> Password:</label>
      <input
        type="password"
        id="password"
        name="password"
        class="form-control"
      />
    </div>

    <div class="form-group">
      <label for="confirm password"> Confirm password:</label>
      <input type="password" name="confirm-password" class="form-control" />
    </div>
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="text" name="email" class="form-control" />
    </div>

    <button type="submit" disabled="true" id="submit" class="btn btn-primary">
      Submit
    </button>
  </form>
</div>

<script src="/js/users/new.js"></script>
{% endblock %}